import pygame as pg

# define colors (R, G, B)
WHITE = (255, 255, 255)
WALL_COLOR = (210, 210, 255)
BLACK = (0, 0, 0)
DARKGREY = (40, 40, 40)
LIGHTGREY = (100, 100, 100)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
SETTING_COLOR = (100, 100, 100)

# grid
TILESIZE = 32
GRIDWIDTH = 928
GRIDHEIGHT = 608

# game settings
HEIGHT = 609
FPS = 60
TITLE = "HCI roguelike Demo"
BGCOLOR = DARKGREY
SETTING_WIDTH = 200
SETTING_HEIGHT = HEIGHT
WIDTH = GRIDWIDTH + SETTING_WIDTH
# gameplay settings
#   player
MIN_START_DISTANCE_PLAYER_ENEMY = 2
MIN_START_DISTANCE_PLAYER_EXIT = 8
#   map generation
MIN_NUM_POWERUP = 1
MAX_NUM_POWERUP = 3
MIN_NUM_OBSTACLE = 2
MAX_NUM_OBSTACLE = 7
MIN_LENGHT_LINE = 1
MAX_LENGHT_LINE = 5
MIN_LINES_FOR_OBSTACLES = 1
MAX_LINES_FOR_OBSTACLES = 4

# custom events
ENEMY_TURN_EVENT = pg.event.custom_type()
PLAYER_SHOOT_EVENT = pg.event.custom_type()

